### ISSUE TITLE
Support for whisper speak.

### ISSUE THREAD

**Issue by MacMeDan** [JanC/TSKit#6]
Looking to support the "Whisper" functionality of the TeamSpeak library. It looks like there are any hooks to the Objective-C Wrapper? My Objective-C is pretty rusty and would appreciate any help on this I can get.

**Comment by MacMeDan** [comment]
@JanC I am getting stuck on creating an array of `UInt64` in my header file. 
I tried 
`@property (nonatomic, copy) NSArray<UInt64 *> *targetClientIDArray;` 
but am getting the error 
 `Type argument 'UInt64 *' (aka 'unsigned long long *') is neither an Objective-C object nor a block type`

**Comment by MacMeDan** [comment]
https://github.com/JanC/TSKit/pull/7

**Comment by JanC** [comment]
thanks for the contribution
